### ISSUE TITLE
Cultures/Religion: Ensure province history for conflicting provinces is correct

### ISSUE THREAD

**Issue by questionmarkexclamationpoint** [ck2plus/CK2Plus_Rewrite#106]
When running the validator, I noticed that we had some duplicate province ids in filenames that conflicted with the vanilla ids. For instance, we had 1468 - Fayoum, when the vanilla province is 1468 - Leh. It looks like we copied some province history from the old CK2+ map. Here are the ids with this issue:

- [ ] 1468
- [ ] 1634
- [ ] 1636
- [ ] 1642
- [ ] 1650
- [ ] 1652
- [ ] 1659
- [ ] 1664
- [ ] 1665
- [ ] 1666
- [ ] 1671
- [ ] 1676
- [ ] 1681
- [ ] 1682
- [ ] 446
- [ ] 803
- [ ] 854

We should make sure the history on all of these is correct.

**Comment by questionmarkexclamationpoint** [comment]
@daniloy Note that the history files for these provinces should be copied from the **vanilla** files, which was the source of this issue to begin with.

**Comment by questionmarkexclamationpoint** [comment]
I've actually just gone ahead and copied the province history for the vanilla files into our repo, so you don't have to worry about that.

**Comment by Whizzer** [comment]
If you didn't already, please take history from FormUpdate.7z. I've fixed several issues inside and fixed most if not all formatting issues Paradox was too lazy to fix.

**Comment by daniloy** [comment]
so uh, the issue is fixed?

**Comment by schwarherz** [comment]
@daniloy I think @questionmarkexclamationpoint said she was going to go through it tonight when she gets on. I'd wait to hear from her for sure.

**Comment by questionmarkexclamationpoint** [comment]
@Whizzer Unfortunately I've already copied the files from vanilla... I guess I could revert the change that copied them all into the repo, and replace them with your files?

**Comment by Whizzer** [comment]
@questionmarkexclamationpoint If that doesn't cause any conflict, I think that would be good idea.

**Comment by schwarherz** [comment]
@questionmarkexclamationpoint Can you clarify the status of this one? Is it done or does it still need done?

**Comment by questionmarkexclamationpoint** [comment]
Sorry, I think this is done. I'll go ahead and close this issue. If I find a more specific problem I will make an issue for it.
