### ISSUE TITLE
Coronation and baptism events 

### ISSUE THREAD

**Issue by LimeKK** [ck2plus/CK2Plus_Rewrite#33]
Only emperor-tier and powerful kings can request Papal coronation/baptism. Depending on distance from Rome, a Papal legate will be send if request is accepted

**Comment by Whizzer** [comment]
Or the ruler should travel to Rome (or wherever the Pope is landed) instead?

**Comment by schwarherz** [comment]
Too loosely defined to expand upon and the author has left. Closing issue.
