### ISSUE TITLE
Buildings: new ideas

### ISSUE THREAD

**Issue by brindza3** [ck2plus/CK2Plus_Rewrite#39]
1.  Special building which represent importance/size of holding. High bonuses to levy size/garrison and tax base with big holdings. Penalty to levy size/garrison and tax base with little/unimportant holdings. Maybe affected by terrain as well. Can be changed by long prosperity,war, epidemics and so on.
2.  More unique buildings(can be altered by Great Works)
3.  More buildings based on terrain(not just stables)
4.  Cultural buildings inspired by HIP mod

**Comment by schwarherz** [comment]
Closing this as the author and assignee is MIA and the idea as it stands is too loosely defined to expand upon.
