### ISSUE TITLE
Laws rewrite - fix problems

### ISSUE THREAD

**Issue by Whizzer** [ck2plus/CK2Plus_Rewrite#40]
After the ambitious rewrite by MightNight, some succession laws are not properly assigned at start-up and some laws' requirements don't properly account for all government types and active DLC.

Furthermore, some succession laws' pass effects seem to activate even when being assigned through automated ways, contrary to the wiki. Hopefully this too can be fixed.

**Comment by schwarherz** [comment]
@Whizzer Is this still needing done or is it fixed?

**Comment by Whizzer** [comment]
Some minor things yet to be done, can probably be closed soon. If we do find more issues in the future, we'll deal with them when they're found.

**Comment by Whizzer** [comment]
@daniloy @LordPeter @questionmarkexclamationpoint 
If any of you want to add three unique retinues to all the new culture groups, feel free to do so. The three for the Georgian group need their potential clause adjusted to match the new internal name.

**Comment by schwarherz** [comment]
Closing pending more issues being found which can be opened as individual issues
