### ISSUE TITLE
Cultures: Italy

### ISSUE THREAD

**Issue by Methaneus** [ck2plus/CK2Plus_Rewrite#55]
- [ ] Assign proper split cultures to the Italian provinces in their history.
- [ ] Assign proper split cultures to people of Italian culture in their history.

**Comment by daniloy** [comment]
I did Southern Italy

**Comment by questionmarkexclamationpoint** [comment]
@daniloy is this done?

**Comment by schwarherz** [comment]
I think this was completed in a recent commit by @daniloy . Closing. Feel free to re-open if not complete.
