### ISSUE TITLE
Titles: Carolingian Empire/Kingdoms

### ISSUE THREAD

**Issue by schwarherz** [ck2plus/CK2Plus_Rewrite#86]
- [x] Add Carolingian Empire title and relevant history

- [x] Add Kingdom of Neustria (France) and relevant history

- [x] Add Kingdom of Austrasia (Germany) and relevant history

**Comment by Whizzer** [comment]
As requested, Kingdom of Arles internally uses k_burgundy, conflating the historic rulers of the two. Should be separated. First ruler of Arles has a bloodline, should be around 936.

**Comment by schwarherz** [comment]
As @Whizzer has this mostly handled, I'm going to mark this as closed. I'll make a new issue for the relevant events and decisions for the rise and fall of the Karling Empire/Kingdoms.
